facelock/models.py
from flask_login import UserMixin
from facelock import db

class Usuario(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.Text)
    email = db.Column(db.Text, unique=True)
    senha = db.Column(db.Text)
    is_admin = db.Column(db.Boolean)
    ativo = db.Column(db.Boolean)
    encoding = db.Column(db.LargeBinary)

    def __init__(self, nome, email, senha, is_admin, encoding, ativo=True):
        self.nome = nome
        self.email = email
        self.senha = senha
        self.is_admin = is_admin
        self.ativo = ativo
        self.encoding = encoding

    def __repr__(self):
        return f"Usuário {self.nome} - Email {self.email}"

facelock/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, PasswordField, BooleanField
from flask_wtf.file import FileField, FileRequired


class RegisterForm(FlaskForm):
    nome = StringField('Nome', validators=[validators.DataRequired()])
    email = StringField("Email", validators=[
                        validators.DataRequired(), validators.Email()])
    password = PasswordField('Senha', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Senhas devem ser iguais')
    ])
    confirm = PasswordField('Repita a Senha')
    is_admin = BooleanField('Administrador')
    ativo = BooleanField('Acesso Ativo?')
    photo = FileField(validators=[FileRequired()])
    submit = SubmitField('Registrar')


class EditForm(FlaskForm):
    nome = StringField('Nome', validators=[validators.DataRequired()])
    email = StringField("Email", validators=[
                        validators.DataRequired(), validators.Email()])
    is_admin = BooleanField('Administrador')
    ativo = BooleanField("Acesso Ativo?")
    submit = SubmitField('Editar')


class PortaForm(FlaskForm):
    submit = SubmitField("Abrir Porta")

facelock/__init__.py
import os
from flask import Flask
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


app = Flask(__name__)

basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SECRET_KEY'] = 'SecretTestKey'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + \
    os.path.join(basedir, 'data.db')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False


db = SQLAlchemy(app)
migrate = Migrate(app, db)

from facelock.models import Usuario

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

from facelock.auth.views import auth_blueprint
from facelock.home.views import home_blueprint


@login_manager.user_loader
def load_user(user_id):
    return Usuario.query.get(int(user_id))

app.register_blueprint(auth_blueprint,url_prefix="/auth")
app.register_blueprint(home_blueprint,url_prefix="/home")

facelock/home/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from facelock import db
from facelock.models import Usuario
from flask_login import login_required, current_user
from facelock.home.forms import RegisterForm, EditForm, PortaForm
from scripts.encode import encode
from scripts.main import relay_on, relay_off
from werkzeug.utils import secure_filename
import bcrypt
import os
import cv2
import time


home_blueprint = Blueprint('home', __name__, template_folder='templates/home')

encodings = {}


# def cacheEncodings():
# encodings = {}
# usuarios = Usuario.query.all()
# for usuario in usuarios:
#   encodings.update((usuario.nome, usuario.encoding))


@home_blueprint.route("/list")
@login_required
def listusers():
    usuarios = Usuario.query.all()
    return render_template('list.html', usuarios=usuarios)


@home_blueprint.route("/new", methods=['GET', 'POST'])
@login_required
def add():
    form = RegisterForm(active=True)
    if request.method == "GET":
        return render_template('add.html', form=form)
    elif request.method == "POST":
        if form.validate_on_submit():
            usuario_encontrado = Usuario.query.filter_by(
                email=form.email.data).all()
            if not usuario_encontrado:
                f = form.photo.data
                filename = secure_filename(f.filename)
                f.save(os.path.abspath(os.path.join(os.path.dirname(
                    __file__), '..', '..', 'training_images', form.nome.data+'.jpg')))
                usuario = Usuario(form.nome.data, form.email.data, bcrypt.hashpw(form.password.data.encode(
                    'utf8'), bcrypt.gensalt()), form.is_admin.data, None, form.ativo.data)
                db.session.add(usuario)
                db.session.commit()
                flash("Usuário Incluído com sucesso", 'success')
                encode()
                # cacheEncodings()
                return redirect(url_for('home.listusers'))
            else:
                flash('Email já cadastrado', 'danger')
        for fieldName, errorMessage in form.errors.items():
            for err in errorMessage:
                print(fieldName)
                flash(err, 'danger')
        return render_template('add.html', form=form)


@home_blueprint.route("/edit/<string:id>", methods=['GET', 'POST'])
@login_required
def edit(id):
    if request.method == 'GET':
        usuario = Usuario.query.get(id)
        form = EditForm(obj=usuario)
        if usuario:
            return render_template('edit.html', usuario=usuario, form=form)
    elif request.method == 'POST':
        print('Entrou')
        form = EditForm()
        usuario = Usuario.query.get(id)
        usuario.nome = form.nome.data
        usuario.email = form.email.data
        usuario.is_admin = form.is_admin.data
        usuario.ativo = form.ativo.data
        db.session.add(usuario)
        db.session.commit()
        flash("Usuário Alterado com sucesso", 'success')
        return redirect(url_for('home.listusers'))


@home_blueprint.route("/delete/<string:id>", methods=['GET'])
@login_required
def delete(id):
    if request.method == 'GET':
        usuario = Usuario.query.get(id)
        if usuario:
            db.session.delete(usuario)
            try:
                os.remove(os.path.abspath(os.path.join(os.path.dirname(
                    __file__), '..', '..', 'training_images', usuario.nome+'.jpg')))
            except:
                flash("Nenhuma imagem associada ao usuario", "warning")
            db.session.commit()
            flash("Usuário removido com sucesso!", "danger")
            encode()
            return redirect(url_for('home.listusers'))


@home_blueprint.route("/feed", methods=['GET', 'POST'])
@login_required
def feed():
    if request.method == 'GET':
        form = PortaForm()
        return render_template('feed.html', form=form)
    elif request.method == 'POST':
        form = PortaForm()
        relay_on()
        time.sleep(1)
        relay_off()
        flash("Abrindo Porta..", 'success')
        return redirect(url_for('home.feed'))

facelock/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Area Administrativa - FaceLock</title>

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
  </head>
<body>
  {% if current_user.is_authenticated %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{{url_for('index')}}">FaceLock</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{{url_for('index')}}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('home.listusers')}}">Lista de Acesso</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('home.add')}}">Adicionar Usuário</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('home.feed')}}">Feed ao vivo</a>
                </li>
             
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth.logout')}}">Logout</a>
                </li>
            </ul>
          </div>
        </nav>
      {% endif%}
      {% for category,mess in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{mess}}
        </div>
      {% endfor %}
      {% block content%}

      {% endblock %}
</body>
<script
src="https://code.jquery.com/jquery-3.4.1.min.js"
integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
crossorigin="anonymous"></script>
<script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
crossorigin="anonymous"
></script>
<script
src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
crossorigin="anonymous"
></script>
</script>
<script
src="{{ url_for('static', filename='js/main.js') }}"
></script>
</html> 