facelock/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, PasswordField, BooleanField
from flask_wtf.file import FileField, FileRequired


class RegisterForm(FlaskForm):
    nome = StringField('Nome', validators=[validators.DataRequired()])
    email = StringField("Email", validators=[
                        validators.DataRequired(), validators.Email()])
    password = PasswordField('Senha', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Senhas devem ser iguais')
    ])
    confirm = PasswordField('Repita a Senha')
    is_admin = BooleanField('Administrador')
    ativo = BooleanField('Acesso Ativo?')
    photo = FileField(validators=[FileRequired()])
    submit = SubmitField('Registrar')


class EditForm(FlaskForm):
    nome = StringField('Nome', validators=[validators.DataRequired()])
    email = StringField("Email", validators=[
                        validators.DataRequired(), validators.Email()])
    is_admin = BooleanField('Administrador')
    ativo = BooleanField("Acesso Ativo?")
    submit = SubmitField('Editar')


class PortaForm(FlaskForm):
    submit = SubmitField("Abrir Porta")

facelock/home/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from facelock import db
from facelock.models import Usuario
from flask_login import login_required, current_user
from facelock.home.forms import RegisterForm, EditForm, PortaForm
from scripts.encode import encode
from scripts.main import relay_on, relay_off
from werkzeug.utils import secure_filename
import bcrypt
import os
import cv2
import time


home_blueprint = Blueprint('home', __name__, template_folder='templates/home')

encodings = {}


# def cacheEncodings():
# encodings = {}
# usuarios = Usuario.query.all()
# for usuario in usuarios:
#   encodings.update((usuario.nome, usuario.encoding))


@home_blueprint.route("/list")
@login_required
def listusers():
    usuarios = Usuario.query.all()
    return render_template('list.html', usuarios=usuarios)


@home_blueprint.route("/new", methods=['GET', 'POST'])
@login_required
def add():
    form = RegisterForm(active=True)
    if request.method == "GET":
        return render_template('add.html', form=form)
    elif request.method == "POST":
        if form.validate_on_submit():
            usuario_encontrado = Usuario.query.filter_by(
                email=form.email.data).all()
            if not usuario_encontrado:
                f = form.photo.data
                filename = secure_filename(f.filename)
                f.save(os.path.abspath(os.path.join(os.path.dirname(
                    __file__), '..', '..', 'training_images', form.nome.data+'.jpg')))
                usuario = Usuario(form.nome.data, form.email.data, bcrypt.hashpw(form.password.data.encode(
                    'utf8'), bcrypt.gensalt()), form.is_admin.data, None, form.ativo.data)
                db.session.add(usuario)
                db.session.commit()
                flash("Usuário Incluído com sucesso", 'success')
                encode()
                # cacheEncodings()
                return redirect(url_for('home.listusers'))
            else:
                flash('Email já cadastrado', 'danger')
        for fieldName, errorMessage in form.errors.items():
            for err in errorMessage:
                print(fieldName)
                flash(err, 'danger')
        return render_template('add.html', form=form)


@home_blueprint.route("/edit/<string:id>", methods=['GET', 'POST'])
@login_required
def edit(id):
    if request.method == 'GET':
        usuario = Usuario.query.get(id)
        form = EditForm(obj=usuario)
        if usuario:
            return render_template('edit.html', usuario=usuario, form=form)
    elif request.method == 'POST':
        print('Entrou')
        form = EditForm()
        usuario = Usuario.query.get(id)
        usuario.nome = form.nome.data
        usuario.email = form.email.data
        usuario.is_admin = form.is_admin.data
        usuario.ativo = form.ativo.data
        db.session.add(usuario)
        db.session.commit()
        flash("Usuário Alterado com sucesso", 'success')
        return redirect(url_for('home.listusers'))


@home_blueprint.route("/delete/<string:id>", methods=['GET'])
@login_required
def delete(id):
    if request.method == 'GET':
        usuario = Usuario.query.get(id)
        if usuario:
            db.session.delete(usuario)
            try:
                os.remove(os.path.abspath(os.path.join(os.path.dirname(
                    __file__), '..', '..', 'training_images', usuario.nome+'.jpg')))
            except:
                flash("Nenhuma imagem associada ao usuario", "warning")
            db.session.commit()
            flash("Usuário removido com sucesso!", "danger")
            encode()
            return redirect(url_for('home.listusers'))


@home_blueprint.route("/feed", methods=['GET', 'POST'])
@login_required
def feed():
    if request.method == 'GET':
        form = PortaForm()
        return render_template('feed.html', form=form)
    elif request.method == 'POST':
        form = PortaForm()
        relay_on()
        time.sleep(1)
        relay_off()
        flash("Abrindo Porta..", 'success')
        return redirect(url_for('home.feed'))

facelock/home/templates/home/add.html
{% extends "base.html"%}

{% block content %}


<form class="form-signin" method="POST" enctype="multipart/form-data">
        <h1>Adicionar Usuário</h1>
    {{ form.hidden_tag()}}
    <div class="form-label-group">
      {{form.nome(class_="form-control")}}
      {{form.nome.label}}
    </div>

    <div class="form-label-group">
      {{form.email(class_="form-control")}}
      {{form.email.label}}
    </div>
    <div class="form-label-group">
        {{form.password(class_="form-control")}}
        {{form.password.label}}
    </div>
    <div class="form-label-group">
        {{form.confirm(class_="form-control")}}
        {{form.confirm.label}}
      </div>
    <div class="form-label-group">
        {{form.is_admin(class_="form-control")}}
        {{form.is_admin.label}}
    </div>
    <div class="form-label-group">
      {{form.ativo(class_="form-control")}}
      {{form.ativo.label}}
    </div>
    <div class="form-label-group">
      {{form.photo(class_="form-control-file-sm")}}
      {{form.photo.label}}
    </div>

    {{form.submit(class="btn btn-lg btn-primary btn-block")}}
</form>

{% endblock %}

facelock/home/templates/home/adduser.html
{% extends "base.html"%}

{% block content %}

<h1>Add User</h1>
{% endblock %}

facelock/home/templates/home/edit.html
{% extends "base.html"%}

{% block content %}



{% if usuario %}

<form class="form-signin" method="POST">
        <h1>Editar Usuário</h1>
        {{ form.hidden_tag()}}
        <div class="form-label-group">
          {{form.nome(class_="form-control")}}
          {{form.nome.label}}
        </div>
  
        <div class="form-label-group">
          {{form.email(class_="form-control")}}
          {{form.email.label}}
        </div>
        <div class="form-label-group">
            {{form.is_admin(class_="form-control")}}
            {{form.is_admin.label}}
        </div>
        <div class="form-label-group">
          {{form.ativo(class_="form-control")}}
          {{form.ativo.label}}
      </div>
  
        {{form.submit(class="btn btn-lg btn-primary btn-block")}}
</form>
   
{% endif%}
{% endblock %}

facelock/home/templates/home/feed.html
{% extends "base.html"%} {% block content%}
<div class=" container">
  <h1>Live Feed Porta</h1>
  <img
    id="video"
    style="width:400px;height:400px"
    src="{{ url_for('video_feed') }}"
  />

  <form class="form-signin" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    {{form.submit(class="btn btn-lg btn-primary btn-block")}}
  </form>
</div>

{% endblock %}

facelock/home/templates/home/index.html
{% extends "base.html"%} {% block content%}

<div class="content container">
  <h1>Seja Bem-Vindo {{ nome }}, a Central de Controle da FaceLock</h1>
</div>

{% endblock %}

facelock/home/templates/home/list.html
{% extends "base.html"%}

{% block content %}

<div class="container content-lista">
    <h1>Lista de Usuários</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Administrador</th>
            <th scope="col">Acesso Ativo</th>
        </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
        <tr>
            <th scope="row">{{usuario.id}}</th>
            <td>{{usuario.nome}}</td>
            <td>{{usuario.email}}</td>
            <td>{{usuario.is_admin}}</td>
            <td>{{usuario.ativo}}</td>
            <td>
                <a href="{{url_for('home.edit', id=usuario.id)}}" class="btn btn-outline-warning">Editar</a>
                <a href="{{url_for('home.delete', id=usuario.id)}}" class="btn btn-outline-danger">Deletar</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
  </table>
</div>


{% endblock %}